---
 - name: Turn off SSH rev DNS lookup
   lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^UseDNS '
      line: UseDNS no

 - name: copy interfaces
   copy: src=config-files/{{scenario}}/{{ansible_hostname}}/interfaces dest=/etc/network/

 - name: restart server to get interfaces working
   shell: sleep 1 && shutdown -r 0
   become: yes
   async: 1
   poll: 0
   ignore_errors: true

 - name: Wait for servers to come back up
   wait_for_connection:
       timeout: 180
       delay: 15

# - name: restart interfaces
#   become: yes
#   command: ifup -a --force

# - name: restart networking
#   service:
#      name: networking
#      state: restarted